name: Publish theme

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: yarn
      - run: yarn build-keycloak-theme
      - uses: actions/upload-artifact@v3
        with:
          name: b2pconnect-keycloak-theme.jar
          path: build_keycloak/target/*
      - name: Create new release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "${{github.run_id}}-${{github.run_number}}-${{github.run_attempt}}"
          files: build_keycloak/target/*
          token: ${{ secrets.TOKEN }}
